import * as fs from "node:fs";
import * as path from "node:path";
import {
  MCP_HINTS_PATH,
  McpUsageSummary,
  CrossSessionSummary,
  workspaceMcpLogPath,
  summarizeMcpUsage,
  summarizeCrossSessionPatterns,
} from "./mcpUsageLog";

// Delimiters for the block written by auto-fix — preserved across writeMcpHints() refreshes.
export const PERMANENT_BLOCK_START = "<!-- permanent-cache-rules -->";
export const PERMANENT_BLOCK_END = "<!-- /permanent-cache-rules -->";

export interface AutoFixResult {
  hotFilesFixed: number;
  hotDirsFixed: number;
  largeFilesFixed: number;
  totalFixed: number;
}

/**
 * Extracts the permanent cache-rules block from `mcp-agent-hints.md`, if present.
 * Returns the raw block string (including delimiters) or empty string when absent.
 */
export function extractPermanentBlock(content: string): string {
  const start = content.indexOf(PERMANENT_BLOCK_START);
  const end = content.indexOf(PERMANENT_BLOCK_END);
  if (start === -1 || end === -1 || end < start) return "";
  return content.slice(start, end + PERMANENT_BLOCK_END.length);
}

/**
 * Reads any existing permanent block from the hints file so callers can
 * preserve it when rewriting session-level hints.
 */
export function readExistingPermanentBlock(): string {
  try {
    if (!fs.existsSync(MCP_HINTS_PATH)) return "";
    return extractPermanentBlock(fs.readFileSync(MCP_HINTS_PATH, "utf-8"));
  } catch {
    return "";
  }
}

/**
 * Analyses the current MCP usage summary and cross-session patterns and writes
 * a `<!-- permanent-cache-rules -->` block to `mcp-agent-hints.md`.
 *
 * The block is placed at the top of the file so agents read it first. If a
 * block already exists it is replaced in-place (idempotent — safe to call
 * multiple times). Session-level hints produced by `writeMcpHints()` are
 * preserved below the permanent block.
 *
 * Covered categories:
 * - Hot files: wasteWarnings (read 3× or more) + persistent cross-session reads
 * - Hot directories: excessiveScans (listed/searched 3× or more)
 * - Large files: files >100KB that should use search_in_file instead of full reads
 */
export function applyMcpAutoFixes(
  summary: McpUsageSummary,
  crossSession: CrossSessionSummary
): AutoFixResult {
  const hotFilePaths = new Set<string>(summary.wasteWarnings.map((w) => w.path));
  const persistentPaths = crossSession.persistentHotFiles.map((f) => f.path);
  for (const p of persistentPaths) hotFilePaths.add(p);

  const hotDirPaths = summary.excessiveScans.map((s) => s.path);
  // Large files not already listed as hot files (no need to repeat the hint).
  const largePaths = summary.largeFiles.map((f) => f.path).filter((p) => !hotFilePaths.has(p));

  const result: AutoFixResult = {
    hotFilesFixed: hotFilePaths.size,
    hotDirsFixed: hotDirPaths.length,
    largeFilesFixed: largePaths.length,
    totalFixed: hotFilePaths.size + hotDirPaths.length + largePaths.length,
  };

  if (result.totalFixed === 0) return result;

  // ── Build the permanent block ─────────────────────────────────────────────
  const lines: string[] = [
    PERMANENT_BLOCK_START,
    "# Permanent cache rules — auto-generated by Claude Skills (edit to adjust)",
    `# Updated: ${new Date().toISOString()}`,
    "",
  ];

  if (hotFilePaths.size > 0) {
    lines.push("## Always cache in memory — never re-read these files");
    for (const p of hotFilePaths) {
      const waste = summary.wasteWarnings.find((w) => w.path === p);
      const cross = crossSession.persistentHotFiles.find((f) => f.path === p);
      const detail = waste
        ? ` — read ${waste.reads}×, ~${waste.wastedTokens.toLocaleString()} tokens wasted`
        : cross
        ? ` — in ${cross.sessionCount}/${cross.totalSessions} sessions, avg ${cross.readsPerSession}×/session`
        : "";
      lines.push(`- \`${p}\`${detail}`);
    }
    lines.push(
      "",
      "→ Rule: these files appear in your context already. Do NOT call read_file on them again.",
      "  If you need a specific line, use search_in_file with a targeted pattern instead.",
      ""
    );
  }

  if (hotDirPaths.length > 0) {
    lines.push("## Never re-scan these directories — cache the listing in context");
    for (const p of hotDirPaths) {
      const sc = summary.excessiveScans.find((s) => s.path === p);
      const detail = sc ? ` — scanned ${sc.scans}× (${sc.estimatedWastedEntries} wasted entries)` : "";
      lines.push(`- \`${p}\`${detail}`);
    }
    lines.push(
      "",
      "→ Rule: call list_directory on these paths at most once per session.",
      "  The dir-cache-guard hook will block repeat scans automatically when active.",
      ""
    );
  }

  if (largePaths.length > 0) {
    lines.push("## Use search_in_file for these large files (>100 KB)");
    for (const p of largePaths) {
      const f = summary.largeFiles.find((lf) => lf.path === p);
      const detail = f ? ` — ${Math.round(f.bytes / 1024)}KB, read ${f.reads}×` : "";
      lines.push(`- \`${p}\`${detail}`);
    }
    lines.push(
      "",
      "→ Rule: do not call read_file on files >100KB. Use search_in_file with a regex,",
      "  or request a specific line range. Full reads consume too many context tokens.",
      ""
    );
  }

  lines.push(PERMANENT_BLOCK_END);
  const newBlock = lines.join("\n");

  // ── Merge with existing hints file ────────────────────────────────────────
  let existing = "";
  try {
    if (fs.existsSync(MCP_HINTS_PATH)) existing = fs.readFileSync(MCP_HINTS_PATH, "utf-8");
  } catch { /* non-fatal */ }

  let updated: string;
  const startIdx = existing.indexOf(PERMANENT_BLOCK_START);
  const endIdx = existing.indexOf(PERMANENT_BLOCK_END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx >= startIdx) {
    // Replace existing block in-place, preserving session hints around it.
    updated =
      existing.slice(0, startIdx) +
      newBlock +
      existing.slice(endIdx + PERMANENT_BLOCK_END.length);
  } else {
    // Prepend — permanent rules first so agents read them before session hints.
    updated = newBlock + (existing ? "\n\n" + existing : "");
  }

  try {
    fs.mkdirSync(path.dirname(MCP_HINTS_PATH), { recursive: true });
    fs.writeFileSync(MCP_HINTS_PATH, updated.trim() + "\n", "utf-8");
  } catch { /* non-fatal */ }

  return result;
}

/**
 * Convenience wrapper that resolves the MCP log path from a workspace root,
 * calls summarizeMcpUsage + summarizeCrossSessionPatterns, then applies auto-fixes.
 * Designed to be called directly from the extension command handler.
 */
export function applyMcpAutoFixesForTarget(workspaceRoot: string): AutoFixResult {
  const wsLogPath = workspaceMcpLogPath(workspaceRoot);
  let logPath: string | undefined;
  try {
    if (fs.existsSync(wsLogPath) && fs.statSync(wsLogPath).size > 0) logPath = wsLogPath;
  } catch { /* fall back to global log */ }
  const summary = summarizeMcpUsage(14, logPath);
  const cross = summarizeCrossSessionPatterns(30, logPath);
  return applyMcpAutoFixes(summary, cross);
}
